In [1]:
import pandas as pd
df = pd.read_csv("data.csv")

In [2]:
df.head()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,H,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            710 non-null    object
 1   Competition       710 non-null    object
 2   Matchday          710 non-null    object
 3   Date              710 non-null    object
 4   Venue             710 non-null    object
 5   Club              710 non-null    object
 6   Opponent          710 non-null    object
 7   Result            710 non-null    object
 8   Playing_Position  652 non-null    object
 9   Minute            710 non-null    object
 10  At_score          710 non-null    object
 11  Type              695 non-null    object
 12  Goal_assist       464 non-null    object
dtypes: object(13)
memory usage: 72.2+ KB

In [4]:
df.describe()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
count,710,710,710,710,710,710,710,710,652,710,710,695,464
unique,21,17,52,468,2,5,129,57,5,106,43,11,91
top,14/15,LaLiga,Group Stage,09-12-15,H,Real Madrid,Sevilla FC,3:00,LW,90,1:00,Right-footed shot,Karim Benzema
freq,61,311,75,5,404,450,27,49,356,17,111,253,44

In [5]:
df['Minute'].isnull().sum()

0